CREATE TABLE IF NOT EXISTS `User` (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `RememberMeToken` (
    token CHAR(36) PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    expiry_timestamp BIGINT NOT NULL,
    CONSTRAINT rememberme_user_fkey FOREIGN KEY (user_id) REFERENCES `User`(id) ON DELETE CASCADE
);