CREATE TABLE IF NOT EXISTS `User` (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `RememberMe` (
    id CHAR(36) PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    expiry_timestamp BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES `User`(id) ON DELETE CASCADE
);